# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventregistryPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceID', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/img/')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField(blank=True, null=True)),
                ('url', models.CharField(max_length=250)),
                ('sourceUrl', models.CharField(max_length=250)),
                ('sourceTitle', models.CharField(max_length=250)),
                ('postUrl', models.CharField(max_length=250)),
                ('lang', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(default='2017-11-30 12:58:10', max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='TweeterPost',
        ),
    ]
