# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0002_auto_20171130_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistrypost',
            name='lang',
        ),
        migrations.AddField(
            model_name='eventregistrypost',
            name='news_id',
            field=models.IntegerField(default=1231231232),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventregistrypost',
            name='created_at',
            field=models.DateTimeField(default='2017-11-30 15:59:26', max_length=150),
        ),
    ]
