# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0003_auto_20171130_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventregistrypost',
            old_name='postUrl',
            new_name='post_url',
        ),
        migrations.RenameField(
            model_name='eventregistrypost',
            old_name='sourceID',
            new_name='source_id',
        ),
        migrations.RenameField(
            model_name='eventregistrypost',
            old_name='sourceTitle',
            new_name='source_title',
        ),
        migrations.RenameField(
            model_name='eventregistrypost',
            old_name='sourceUrl',
            new_name='source_url',
        ),
        migrations.AlterField(
            model_name='eventregistrypost',
            name='created_at',
            field=models.DateTimeField(default='2017-11-30 16:01:07', max_length=150),
        ),
    ]
