# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0005_auto_20171130_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventregistrypost',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='eventregistrypost',
            old_name='post_url',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='eventregistrypost',
            name='created_at',
            field=models.DateTimeField(default='2017-12-01 21:20:35', max_length=150),
        ),
    ]
