# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0006_auto_20171201_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistrypost',
            name='created_at',
            field=models.DateTimeField(default='2017-12-02 12:08:45', max_length=150),
        ),
    ]
