# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0010_auto_20171208_1909'),
    ]

