# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0011_auto_20171213_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistrypost',
            name='created_at',
            field=models.DateTimeField(default='2017-12-13 20:49:47', max_length=150),
        ),
    ]
