# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0013_auto_20171213_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistrypost',
            name='created_at',
            field=models.DateTimeField(default='2017-12-13 20:51:31', max_length=150),
        ),
        migrations.AlterField(
            model_name='eventregistrypost',
            name='tags',
            field=models.CharField(default='Fake News', max_length=250),
        ),
    ]
